id: os_config_data_install_enforce
title: "Enforce Installation of XProtect Remediator and Gatekeeper Updates Automatically"
discussion: |
  Software Update _MUST_ be configured to update XProtect Remediator and Gatekeepr automatically.

  This setting enforces definition updates for XProtect Remediator and Gatekeeper; with this setting in place, new malware and adware that Apple has added to the list of malware or untrusted software will not execute. These updates do not require the computer to be restarted.
  
  link:https://support.apple.com/en-us/HT207005[]

  NOTE: Software update will automatically update XProtect Remediator and Gatekeeper by default in the macOS.
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.SoftwareUpdate')\
  .objectForKey('ConfigDataInstall').js
  EOS
result:
  string: "true"
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-91774-0
  cci: 
    - N/A
  800-53r5:
    - SI-3
    - SI-2(5)
  800-53r4:
    - N/A
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r2:
    - 3.14.1
    - 3.14.2
    - 3.13.3
  cis:
    benchmark:
      - 1.6 (level 1)
    controls v8:
      - 10.1
      - 10.2
      - 10.4
  hipaa:
    - 164.306(a)(2)      
macOS:
  - "13.0"
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - cis_lvl1
  - cis_lvl2
  - cisv8
  - hipaa
severity: "high"
mobileconfig: true
mobileconfig_info:
  com.apple.SoftwareUpdate:
    ConfigDataInstall: true
